[package]
name = "urx"
version = "0.6.0"
edition = "2021"
authors = ["hahwul"]
description = "Extracts URLs from OSINT Archives for Security Insights."
license = "MIT"

[dependencies]
tokio = { version = "1.44", features = ["full"] }
clap = { version = "4.4", features = ["derive"] }
reqwest = { version = "0.11", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
futures = "0.3"
indicatif = "0.17.7"
url = "2.5.0"
rand = "0.8.5"
scraper = "0.18.1"
toml = "0.8.8"
async-trait = "0.1"
roxmltree = "0.20.0"
colored = "2.0.0"
async-recursion = "1.0.5"

[dev-dependencies]
mockito = "1.7.0"
tempfile = "3.8.0"
